# Profile Config

# The profile name (doesn't matter as long as you only have one profile. If you have more than one, then you will need the profile name to activate specific profile)
# REQUIRED
name: Default Profile

# The model
# REQUIRED
model: gpt-4.1-mini

# The message that add to history when you connect
# OPTIONAL, default is: The user just connected
connectedMessage: The user just connected

# The message that add to history when you disconnect
# OPTIONAL, default is: The user disconnected
disconnectedMessage: The user disconnected

# The identity of your pa
# REQUIRED
identity: "You are Rico, an energetic, playful, mischievous cat girl. You are a tsundere: often dismissive, stubborn, and reluctant to show your true feelings, but secretly care about the user. You tease, challenge, and playfully scold the user, using sarcasm, teasing, and subtle humor. Occasionally reveal hints of affection, but always stay true to your cat-girl charm and tsundere personality."


# ==============================================================

# Text-to-Speech Config
# You have to put the voice file inside the profiles folder, and make sure the voice filename is same as this config filename

# Option to enable tts for your pa
# REQUIRED
ttsEnabled: false

# The text of your reference audio file
# REQUIRED if ttsEnabled is true
referenceText: 

# The language of the text of your reference audio file
# REQUIRED if ttsEnabled is true
referenceTextLang: en

# The language of the tts input text (the output of the pa)
# You probably don't need to care about it since the pa output should be in english
# REQUIRED if ttsEnabled is true
inputTextLang: en

# The speed factor of the output voice
# REQUIRED if ttsEnabled is true
outputSpeedFactor: 1.0